### PR TITLE
Fix example `capture.py`

### PR DESCRIPTION
**Pull request by hartwork**
Hi, thanks for [`examples/capture.py`](https://github.com/selectel/pyte/blob/master/examples/capture.py)! :pray: 

While playing with it I discovered three key issues about it and felt like offering a pull request with fixes to give back. These issues were:
- Unhandled exception `OSError`
- Providing an environment lacking `HOME`

As a bonus I resolved a needless `else` to reduce nesting and make the structure a bit simpler. Review on commit level is probably most efficient.

What do you think?

### CODE REVIEW

**Comment by hartwork** [comment]
@selectel I believe this is ready for merge now. What do you think?

**Comment by superbobry** [comment]
Thanks, Sebastian.

@selectel does not maintain this repo, sadly. It's just me checking in once in a while.

**Comment by hartwork** [comment]
@superbobry thanks for the merge! Has it been considered to move/transfer the repository to your account?

**Comment by superbobry** [comment]
I very much want @selectel to relicense pyte under a more permissive license first, and then transfer to another org/account.

Ping @tnt-dev :)

**Pull request merged**
